application: instahust
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# - url: /css
#   static_dir: static/css

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?local_settings\.py